#!/usr/bin/env python


import codecs
import sys


def usage():
    print("recommend-items like_items=\"item1,item2,...\"")


def read_frequent_items():
    ret = []
    for line in codecs.open('/data/high_freq_items.csv'):
        ret.append(line.split(',')[0])
    return ret


def read_rules():
    ret = []
    for line in codecs.open('/weka_results/association_rules.txt', encoding='utf-8'):
        left, right = line.split('==>')
        ret.append((left.split(',')[:-1], right.split(',')[:-1]))
    return ret


if __name__ == '__main__':
    if len(sys.argv) != 2 or not sys.argv[1].startswith("like_items="):
        usage()
        sys.exit()
    freq_items = read_frequent_items()
    rules = read_rules()
    likes = sorted(sys.argv[1][6:].split(','))
    result = []
    for rule in rules:
        for like in likes:
            if like in freq_items and not like in rule[0]:
                break
        else:
            result += rule[1]
    for like in set(result):
        print like
